"""
Drug false positive filtering constant sets.

This module contains curated constant sets used by DrugFalsePositiveFilter to
identify common false positives in drug name detection. Includes bacteria,
biological entities, common words, and other non-drug terms.

Key Components:
    - BACTERIA_ORGANISMS: Bacteria and virus names (common in vaccine trials)
    - BIOLOGICAL_ENTITIES: Proteins, enzymes, cell types
    - BIOLOGICAL_SUFFIXES: Suffixes indicating non-drug biological terms
    - BODY_PARTS: Anatomical terms
    - COMMON_WORDS: Generic terms that aren't drugs
    - CREDENTIALS: Academic/medical credentials
    - DRUG_ABBREVIATIONS: Valid drug abbreviations to preserve
    - EQUIPMENT_PROCEDURES: Medical equipment and procedure names
    - FP_SUBSTRINGS: Substrings indicating false positives
    - NER_FALSE_POSITIVES: Terms causing NER false positives
    - NON_DRUG_ALLCAPS: All-caps terms that aren't drugs
    - ORGANIZATIONS: Organization names
    - PHARMA_COMPANY_NAMES: Company names (not drugs themselves)
    - TRIAL_STATUS_TERMS: Clinical trial status terminology
    - VACCINE_TERMS: Vaccine-related terms
    - ALWAYS_FILTER: Terms to always filter regardless of context

Example:
    >>> from C_generators.C26_drug_fp_constants import BACTERIA_ORGANISMS
    >>> "influenza" in BACTERIA_ORGANISMS
    True

Dependencies:
    None (pure constant definitions)
"""

from __future__ import annotations

from typing import Dict, List, Set


# Bacteria names (often appear in vaccine trial data, not drugs)
BACTERIA_ORGANISMS: Set[str] = {
    # Bacteria commonly in vaccine trials
    "neisseria meningitidis",
    "streptococcus pneumoniae",
    "haemophilus influenzae",
    "escherichia coli",
    "e. coli",
    "staphylococcus aureus",
    "s. aureus",
    "clostridium difficile",
    "c. difficile",
    "mycobacterium tuberculosis",
    "bordetella pertussis",
    "salmonella typhi",
    "vibrio cholerae",
    "corynebacterium diphtheriae",
    "shigella",
    "listeria monocytogenes",
    "legionella pneumophila",
    "pseudomonas aeruginosa",
    "klebsiella pneumoniae",
    "enterococcus",
    "helicobacter pylori",
    "h. pylori",
    # Viruses (not drugs)
    "influenza",
    "coronavirus",
    "sars-cov-2",
    "hepatitis",
    "hiv",
    "herpes",
    "measles",
    "mumps",
    "rubella",
    "varicella",
    "rotavirus",
    "polio",
    "rabies",
    "yellow fever",
    "dengue",
    "zika",
    "ebola",
    "rsv",
}

# Vaccine-related terms (not drugs per se)
VACCINE_TERMS: Set[str] = {
    "meningococcal",
    "pneumococcal",
    "conjugate vaccine",
    "polysaccharide vaccine",
    "inactivated vaccine",
    "live attenuated",
    "mrna vaccine",
    "viral vector",
    "subunit vaccine",
    "toxoid",
    "antigen",
    "adjuvant",
    "immunization",
    "vaccination",
    "booster",
    "serogroup",
    "serotype",
}

# Credentials and titles (not drugs)
CREDENTIALS: Set[str] = {
    "md",
    "phd",
    "mph",
    "mbbs",
    "frcp",
    "do",
    "rn",
    "np",
    "pa",
    "pharmd",
    "dnp",
    "dpt",
    "ms",
    "ma",
    "msc",
    "bsc",
    "ba",
}

# Biological entities (proteins, complexes, pathways - not drugs)
BIOLOGICAL_ENTITIES: Set[str] = {
    # Complement system components (biological, not drugs)
    "c3",
    "c4",
    "c5",
    "c3b",
    "c4b",
    "c5b",
    "c3a",
    "c5a",
    "c3 convertase",
    "c5 convertase",
    "membrane attack complex",
    "mac",
    "terminal complement complex",
    "alternative pathway",
    "classical pathway",
    "lectin pathway",
    # Receptors and kinases (biological targets, not drugs)
    "musk",  # Muscle-Specific Kinase - often mislinked to "musk deer"
    "achr",  # Acetylcholine receptor
    "fcrn",  # Neonatal Fc receptor
    "fc receptor",
    "ache",  # Acetylcholinesterase
    "acetylcholinesterase",
    "acetylcholine esterase",  # variant spelling
    "acetylcholine receptor",
    "cholinergic receptors",
    "anti-acetylcholine receptor antibody",  # biomarker, not drug
    # Autoantibody phrases (diagnostic markers, not drugs)
    "anti-neutrophil cytoplasmic antibody",
    "anti-neutrophil cytoplasmic antibodies",
    "antineutrophil cytoplasmic antibody",
    "antineutrophil cytoplasmic antibodies",
    "anti-citrullinated protein antibody",
    "anti-citrullinated protein antibodies",
    "antinuclear antibody",
    "antinuclear antibodies",
    # Hormones (biological, not therapeutic drugs unless specific formulation)
    "fsh",  # Follicle Stimulating Hormone
    "follicle stimulating hormone",
    "follicle-stimulating hormone",
    # Immunoglobulins (biological markers)
    "igg",
    "iga",
    "igm",
    "ige",
    "igd",
    "igg1",
    "igg2",
    "igg3",
    "igg4",
    # Cytokines and growth factors (biological)
    "tnf",
    "tnf-alpha",
    "tnf-α",
    "interferon",
    "ifn",
    "ifn-gamma",
    "ifn-γ",
    "interleukin",
    "il-1",
    "il-2",
    "il-6",
    "il-10",
    "tgf-beta",
    "tgf-β",
    "vegf",
    "egf",
    "fgf",
    "pdgf",
    # Enzymes and proteins
    "crp",
    "ldh",
    "ast",
    "alt",
    "alp",
    "ggt",
    "lipase",
    "amylase",
    "transferase",
    "kinase",
    "phosphatase",
    "protease",
    # Cellular components
    "mitochondria",
    "ribosome",
    "endoplasmic reticulum",
    "golgi",
    "nucleus",
    "cytoplasm",
    "membrane",
    "receptor",
    "channel",
    "transporter",
    # Lab markers (not drugs)
    "hemoglobin",
    "hematocrit",
    "platelet",
    "neutrophil",
    "lymphocyte",
    "monocyte",
    "eosinophil",
    "basophil",
    "albumin",
    "globulin",
    "bilirubin",
    "urea",
    "creatinine",
    "potassium",
    "sodium",
    "calcium",
    "magnesium",
    "phosphate",
    "chloride",
    "bicarbonate",
    # Lipid panel / metabolic markers (lab values, not drugs)
    "cholesterol",
    "ldl",
    "hdl",
    "triglycerides",
    "triglyceride",
    "sgpt",  # Serum Glutamic-Pyruvic Transaminase (liver enzyme)
    # Kidney function markers (lab values, not drugs)
    "egfr",  # estimated Glomerular Filtration Rate
    "gfr",   # Glomerular Filtration Rate
    "upcr",  # Urine Protein-Creatinine Ratio
    "uacr",  # Urine Albumin-Creatinine Ratio
    "proteinuria",
    "microalbuminuria",
    "macroalbuminuria",
}

# Pharmaceutical company names (not drugs)
PHARMA_COMPANY_NAMES: Set[str] = {
    # Major pharma companies
    "novartis",
    "pfizer",
    "roche",
    "merck",
    "johnson",
    "johnson & johnson",
    "astrazeneca",
    "sanofi",
    "gsk",
    "glaxosmithkline",
    "abbvie",
    "amgen",
    "gilead",
    "eli lilly",
    "lilly",
    "bristol-myers squibb",
    "bms",
    "bayer",
    "boehringer ingelheim",
    "takeda",
    "novo nordisk",
    "regeneron",
    "biogen",
    "vertex",
    "moderna",
    # Specialty/biotech companies often in clinical trials
    "alexion",
    "biocryst",
    "biocryst pharmaceuticals",
    "chemocentryx",
    "achillion",
    "achillion pharmaceuticals",
    "catalyst biosciences",
    "catalyst",
    "gyroscope therapeutics",
    "gyroscope",
    "silence therapeutics",
    # Other common false positives
    "pharmaceuticals",
    "therapeutics",
    "biosciences",
    "biopharma",
}

# Common words that might match drug names
COMMON_WORDS: Set[str] = {
    # Dosage forms and containers
    "oral",
    "tablet",
    "capsule",
    "injection",
    "solution",
    "cream",
    "gel",
    "patch",
    "spray",
    "drops",
    "vial",
    "vials",
    "ampoule",
    "ampule",
    "syringe",
    "kit",
    # Generic substances
    "water",
    "salt",
    "acid",
    "base",
    "oil",
    "sugar",
    "fat",
    # Metals (often false positives)
    "iron",
    "gold",
    "silver",
    "lead",
    "zinc",
    # Drug-related terms
    "dose",
    "drug",
    "agent",
    "compound",
    "product",
    "formula",
    "active",
    "inactive",
    "medications",
    "medication",
    "medicine",
    "medicines",
    "treatment",
    "therapy",
    # Generic/vague terms
    "various",
    "other",
    "others",
    "complete",
    "unknown",
    "none",
    "same",
    "different",
    "several",
    "many",
    "some",
    "all",
    "any",
    # Common English words that appear in RxNorm (false positives)
    "boston",
    "date",
    "dates",
    "prevail",
    "bronchial",
    "purpose",
    "vital",
    "tbc",
    "tbd",
    "maintain",
    "program",
    "perform",
    "impact",
    "basis",
    "barrier",
    "deliver",
    "syringe",
    "needle",
    "tape",
    "mask",
    "matrix",
    "regain",
    "supply",
    "correct",
    "corrective",
    "throat",
    "schirmer",
    "stop",
    "align",
    "fig",
    "val",
    "sinus",
    "excel",
    "nasal",
    "pediatric",
    "tums",
    "induction",
    # Medical equipment/supplies (not drugs)
    "pregnancy test",
    "hbsag",
    "hbs",
    # Journal/publication names
    "lancet",
    "nature",
    "science",
    "cell",
    # Geographic/organization names (not drugs)
    "turkey",
    "genesis",
    "urban",
    # Generic medical terms
    "promote",
    "cartilage",
    "bone marrow",
    "lymphocytes",
    "no data",
    "arthritis foundation",
    # Clinical questionnaire abbreviations (not drugs)
    "maf",  # Multidimensional Assessment of Fatigue questionnaire
    "hads",  # Hospital Anxiety and Depression Scale
    "sf-36",  # Short Form 36 questionnaire
    "eq-5d",  # EuroQol 5-Dimension questionnaire
    "sf-12",  # Short Form 12 questionnaire
    "phq-9",  # Patient Health Questionnaire-9
    "gad-7",  # Generalized Anxiety Disorder-7
    "vas",  # Visual Analog Scale
    "nrs",  # Numeric Rating Scale
    "facit",  # Functional Assessment of Chronic Illness Therapy
    "promis",  # Patient-Reported Outcomes Measurement Information System
    # Antibody types (markers, not drugs unless specific)
    "anca",
    # Generic process/action words
    "via",
    "met",
    "food",
    "duration",
    "support",
    "root",
    "process",
    "his",
    "central",
    "ensure",
    "blockade",
    "therapeutic",
    "monotherapy",
    "targeted therapy",
    "soc",
    # Common English words that happen to be drug brand names
    "today",  # TODAY is a brand for nonoxynol-9 contraceptive
    "choice",  # Various brand names
    "plan",  # Plan B
    "clear",
    "complete",
    "simple",
    "natural",
    "daily",
    "one",
    "first",
    "total",
    # Disease abbreviations that are also in RxNorm (prefer disease meaning)
    "pah",  # Pulmonary Arterial Hypertension (not Phenylalanine)
    "als",  # Amyotrophic Lateral Sclerosis (not Aluminum Salt)
    "ms",   # Multiple Sclerosis (not Morphine Sulfate in most contexts)
    "hiv",  # Human Immunodeficiency Virus
    # Biomolecules (not drugs per se)
    "protein",
    "creatinine",
    "glucose",
    "angiotensin",
    "aldosterone",
    "renin",
    "renin–",
    "complement",
    "factor b",
    "serum",
    # Too generic drug terms
    "inhibitor",
    "inhibitors",
    "antagonist",
    "antagonists",
    "agonist",
    "agonists",
    "receptor",
    "receptors",
    "pharmaceutical preparations",
    "activation product",
    # Anatomical/biological structures
    "nephron",
    "membrane attack complex",
    "com",
    "importal",
    # Animals and biological terms
    "animals",
    "animal",
    "mice",
    "mouse",
    "rat",
    "rats",
    "dog",
    "dogs",
    "monkey",
    "monkeys",
    "rabbit",
    "rabbits",
    # Medical symptoms/processes (not drugs)
    "constriction",
    "dilation",
    "stenosis",
    "obstruction",
    "occlusion",
    "inflammation",
    "infection",
    "hemorrhage",
    "bleeding",
    # Common first names that appear in press releases (not drugs)
    "julie",
    "peter",
    "john",
    "david",
    "michael",
    "james",
    "robert",
    "william",
    "richard",
    "thomas",
    "mary",
    "patricia",
    "jennifer",
    "linda",
    "elizabeth",
    "barbara",
    "susan",
    "sarah",
    "karen",
    "nancy",
    "nikki",
    "ayn",
    # Generic medical/scientific terms (not specific drugs)
    "vaccines",  # Generic term, not a specific drug
    "vaccine",
    "protection",  # Common word, not Protectin
    "protections",
    # Disease/clinical abbreviations wrongly matched to drugs
    "ctd",  # Connective Tissue Diseases (not a drug)
    # WHO Functional Class designations (clinical classification, not drugs)
    "fc",
    "fc i",
    "fc ii",
    "fc iii",
    "fc iv",
    # Common statistical abbreviations that get misread
    "cls",  # Often misread from "CIs" (confidence intervals)
    "cis",  # Confidence intervals
    # Common measurement abbreviations
    "mm",   # millimeters (credential or unit, not drug)
    "cm",   # centimeters
    "kg",   # kilograms
    "mg",   # milligrams (unit, not drug name)
    "ml",   # milliliters
    # Consumer/social media FPs (CADEC corpus - non-drug terms in patient forums)
    "sleep",
    "cold",
    "cough",
    "statin",  # drug class, not specific drug
    "dry eyes",
    "dry skin",
    "pain relief",
    "once a day",
    "sore throat",
    "milk",
    "ice",
    "fiber",
    "bear",
    "grapefruit juice",
    "grape juice",
    "cider vinegar",
    "rice",
    "salmon",
    "wool",
    "wheelchair",
    "tomorrow",
    "tube",
    "switch",
    "burn",
    "rectal",
    "gloves",
    "acne",
    "ten",
    "let",
    "dna",
    "mos",
}

# Organizations and agencies (not drugs)
ORGANIZATIONS: Set[str] = {
    "medicines agency",
    "european medicines agency",
    "ema",
    "fda",
    "food and drug administration",
    "world health organization",
    "who",
    "nih",
    "national institutes of health",
    "cdc",
    "centers for disease control",
}

# Body parts and organs (not drugs)
BODY_PARTS: Set[str] = {
    "liver",
    "kidney",
    "heart",
    "lung",
    "brain",
    "blood",
    "bone",
    "skin",
    "muscle",
    "nerve",
    "eye",
    "ear",
    "stomach",
    "intestine",
    "colon",
    "bladder",
    "spleen",
    "pancreas",
    "thyroid",
    "adrenal",
    "ovary",
    "uterus",
    "prostate",
    "breast",
    "tongue",
    "teeth",
    "gum",
    "nail",
    "hair",
    "hip",
    "disc",
}

# Clinical trial status terms (leaked from trial data)
TRIAL_STATUS_TERMS: Set[str] = {
    "not_yet_recruiting",
    "recruiting",
    "active",
    "completed",
    "suspended",
    "terminated",
    "withdrawn",
    "enrolling",
    "available",
    "approved",
    "no_longer_available",
    "withheld",
    "unknown",
    "not yet recruiting",
    "active, not recruiting",
    "enrolling by invitation",
}

# Medical equipment/procedures (not drugs)
EQUIPMENT_PROCEDURES: Set[str] = {
    "ultrasound",
    "mri",
    "ct",
    "xray",
    "x-ray",
    "scan",
    "surgery",
    "biopsy",
    "endoscopy",
    "catheter",
    "stent",
    "implant",
    "pacemaker",
    "ventilator",
    "dialysis",
    "ecg",
    "ekg",
    "eeg",
    "emg",
    "blood test",
    "blood tests",
}

# Terms that should ALWAYS be filtered, even from specialized lexicons
ALWAYS_FILTER: Set[str] = {
    "medications",
    "medication",
    "other",
    "others",
    "placebo",
    "control",
    "standard of care",
    "standard care",
    "best supportive care",
    "usual care",
    "no intervention",
    "observation",
    "watchful waiting",
    "dietary supplement",
    "behavioral",
    "device",
    "procedure",
    "radiation",
    "biological",
    "combination product",
    "diagnostic test",
    "genetic",
    "various",
    "multiple",
    "unspecified",
    "investigational",
    "experimental",
    "study drug",
    "study treatment",
    "test drug",
    "test product",
    "active comparator",
    "sham comparator",
}

# NER-specific false positives (commonly returned by scispacy UMLS)
NER_FALSE_POSITIVES: Set[str] = {
    # Generic pharmaceutical terms
    "pharmaceutical preparations",
    "pharmaceutical",
    "pharmaceuticals",
    "drug",
    "drugs",
    "medicine",
    "medicines",
    "therapeutic",
    "therapeutics",
    "medicament",
    "medicaments",
    "preparation",
    "preparations",
    "formulation",
    "formulations",
    "compound",
    "compounds",
    "agent",
    "agents",
    "substance",
    "substances",
    # Drug classes (not specific drugs)
    "angiotensin-converting enzyme inhibitors",
    "ace inhibitors",
    "beta blockers",
    "beta-blockers",
    "calcium channel blockers",
    "diuretics",
    "statin",
    "statins",
    "nsaids",
    "antibiotics",
    "antivirals",
    "antifungals",
    "analgesics",
    "antipyretics",
    "anticoagulants",
    "antihistamines",
    "antidepressants",
    "antipsychotics",
    "anxiolytics",
    "sedatives",
    "hypnotics",
    "stimulants",
    "opioids",
    "opiates",
    "barbiturates",
    "benzodiazepines",
    "corticosteroid",  # class, not specific drug
    "glucocorticoid",
    "glucocorticoids",
    "mineralocorticoid",
    "mineralocorticoids",
    "immunosuppressive agents",
    "immunosuppressants",
    "immunomodulators",
    "chemotherapeutic agents",
    "chemotherapy",
    "cytotoxic agents",
    "targeted therapy",
    "monotherapy",
    "combination therapy",
    "first-line therapy",
    "second-line therapy",
    "salvage therapy",
    "maintenance therapy",
    "induction therapy",
    "consolidation therapy",
    # Biological entities (NOT drugs)
    "complement system proteins",
    "complement proteins",
    "complement inactivating agents",
    "complement factor b",
    "complement c3 convertases",
    "complement c5 convertases",
    "complement component",
    "complement inhibition",
    # Lab reagents (not therapeutic drugs)
    "sds",
    "sodium dodecyl sulfate",
    "anaphylatoxins",
    "membrane attack complex",
    "serum proteins",
    "plasma proteins",
    "blood proteins",
    "growth factors",
    "cytokines",
    "chemokines",
    "interleukins",
    "interferons",
    "tumor necrosis factor",
    "receptors",
    "receptor",
    "transporter",
    "transporters",
    "channel",
    "channels",
    "enzyme",
    "enzymes",
    "kinase",
    "kinases",
    "phosphatase",
    "phosphatases",
    "protease",
    "proteases",
    "ligand",
    "ligands",
    "substrate",
    "substrates",
    "cofactor",
    "cofactors",
    "coenzyme",
    "coenzymes",
    "antigen",
    "antigens",
    "antibody",
    "antibodies",
    "immunoglobulin",
    "immunoglobulins",
    "immunoglobulin g",  # biomarker, not drug
    "immunoglobulin a",
    "immunoglobulin m",
    "immunoglobulin e",
    # Specific NER false positives observed
    "importal",  # Laxative, not relevant to trials
    "antagon",  # False match
    "sc5b-9 protein complex",
    "serum, horse",
    "horse serum",
    "serum",
    "plasma",
    "blood",
    "tissue",
    "cell",
    "cells",
    "protein",
    "proteins",
    "peptide",
    "peptides",
    "amino acid",
    "amino acids",
    "nucleotide",
    "nucleotides",
    "lipid",
    "lipids",
    "carbohydrate",
    "carbohydrates",
    "activation product",
    "activation products",
    "degradation product",
    "degradation products",
    "metabolite",
    "metabolites",
    "soc",  # Standard of Care
    # Hormone-related (biological, not drugs unless specific)
    "hormone",
    "hormones",
    "adrenal cortex hormones",
    "steroid hormones",
    "thyroid hormones",
    "pituitary hormones",
    "fsh",
    "follicle stimulating hormone",
    "follicle-stimulating hormone",
    "human follicle-stimulating hormone",
    "renin",
    "aldosterone",
    "angiotensin",
    "epinephrine",
    "norepinephrine",
    "dopamine",
    "serotonin",
    "histamine",
    "acetylcholine",
    "acetylcholine esterase",
    "anti-acetylcholine receptor antibody",
    # Receptor types (biological targets, not drugs)
    "receptors, corticosteroid",
    "serotonin antagonists",
    "serotonin receptors",
    "dopamine receptors",
    "histamine receptors",
    "adrenergic receptors",
    "cholinergic receptors",
    "opioid receptors",
    "epidermal growth factor receptor",
    "vascular endothelial growth factor",
    "platelet-derived growth factor",
    "fibroblast growth factor",
    "insulin-like growth factor",
    "transforming growth factor",
    # Inhibitor classes (not specific drugs)
    "ras inhibitor",
    "ras inhibitors",
    "factor xa inhibitors",
    "thrombin inhibitors",
    "protease inhibitors",
    "kinase inhibitors",
    "mtor inhibitors",
    "jak inhibitors",
    "tyrosine kinase inhibitors",
    "hdac inhibitors",
    "parp inhibitors",
    # Transporter types
    "sodium-glucose transporter 1",
    "sodium-glucose transporter 2",
    "glucose transporters",
    "ion channels",
    "calcium channels",
    "sodium channels",
    "potassium channels",
    # Other biological
    "ccrl1 protein, human",
    "ccrl1 protein",
    "human protein",
    # Observed NER false positives
    "colicin plasmids",
    "wright stain",
    "rheumatoid factor",
    "dbl oncoprotein",
    "prevent (product)",
    "prevent product",
    "glycophorin a",
    "nervous system involved sulfotransferase",
    "estrogens, non-steroidal",
    "musk secretion from musk deer",
    "ldl-receptor related protein 1",
    "glycation end products, advanced",
    "stop brand of fluoride",
    "gastrointestinal agents",
    # Drugs of abuse / controlled substances (not trial drugs unless specific formulation)
    "cocaine",
    "cocaine (substance)",
    "heroin",
    "methamphetamine",
    "cannabis",
    "marijuana",
    "morphine",  # Unless specific formulation
    "fentanyl",  # Unless specific formulation
    # Muscle-specific kinase variants (often confused with animal product)
    "musk",
    "musk secretion",
    "musk deer",
    # Additional false positives from clinical trial protocols
    "immune complex",
    "fc receptor",
    "autoantibodies",
    "biological factors",
    "investigational new drugs",
    "antibodies, anti-idiotypic",
    # Additional NER false positives observed in Iptacopan trial
    "sodium-glucose transporter 1",
    "sodium-glucose cotransporter-2",
    "at1 receptor blockers",
    "c5a anaphylatoxins",
    "c3 activation products",
    "normal serum c3",
    "complement bio",
    "medicines agency",
    # Generic amino acids (not drugs)
    "alanine",
    "tyrosine",
    "proline",
    "histidine",
    "l-histidine",
    "glycine",
    "aspartate",
    "serine",
    "threonine",
    "leucine",
    "isoleucine",
    "valine",
    "phenylalanine",
    "tryptophan",
    "methionine",
    "cysteine",
    "asparagine",
    "glutamine",
    "glutamate",
    "arginine",
    "lysine",
    # Biochemical components / excipients
    "sucrose",
    "polysorbate 80",
    "polysorbates",
    "hydrochloride",
    "inosine monophosphate",
    "trientine",  # Chelating agent, often false positive
    # Additional NER false positives observed in myasthenia gravis protocols
    "alanine transaminase",
    "complement component c1",
    "c1s protein, human",
    "c1s protein",
    "human follicle-stimulating hormone",
    "ldl-receptor related protein 1",
    "ldl receptor",
    # Statistical/ML terms commonly misidentified as drugs
    "lasso",
    "metric",
    "metric (substance)",
    "metrics",
    "correlation",
    "coefficient",
    "regression",
    "classifier",
    "model",
    "algorithm",
    "variance",
    "covariance",
    "standard deviation",
    "confidence interval",
    "hazard ratio",
    "odds ratio",
    # Author name patterns that get mismatched to drugs
    "fluorouracil",  # Often matched to "Fu Y" (author name)
    "antigens, cd15",  # Often matched to "Lewis JH" (author name)
    # Equipment/scanner brand names
    "revolution",
    "somatom",
    "aquilion",
    # Generic clinical terms (not drugs)
    "therapeutic intervention",
    "induction",
    "intervention",
    "interventions",
    # Enzymes/proteins commonly misidentified as drugs
    "alkaline phosphatase",
    "myeloperoxidase",
    "proteinase 3",
    "proteinase",
    "aspartate aminotransferase",
    "aspartate transaminase",
}

# Generic all-caps words that are not drugs
NON_DRUG_ALLCAPS: Set[str] = {
    "information",
    "complete",
    "ring",
    "same",
    "other",
    "none",
    "all",
    "any",
    "new",
    "old",
    "high",
    "low",
    "full",
    "empty",
    "open",
    "closed",
    "start",
    "end",
    "first",
    "last",
    "next",
    "previous",
    "current",
    "total",
    "average",
    "mean",
    "median",
    "normal",
    "abnormal",
    "positive",
    "negative",
    "present",
    "absent",
    "available",
    "unavailable",
    "required",
    "optional",
    "primary",
    "secondary",
    "additional",
    "hads",
    "maf",
    "pro",
}

# Pattern suffixes that indicate biological entities, not specific drugs
BIOLOGICAL_SUFFIXES: List[str] = [
    " protein",
    " proteins",
    " receptor",
    " receptors",
    " inhibitor",
    " inhibitors",
    " antagonist",
    " antagonists",
    " agonist",
    " agonists",
    " blocker",
    " blockers",
    " transporter",
    " transporters",
    " channel",
    " channels",
    " enzyme",
    " enzymes",
    " kinase",
    " kinases",
    " factor",
    " factors",
    " complex",
    " pathway",
    " system",
    " agents",
    " products",
    " product",
    ", human",
    ", mouse",
    ", rat",
]

# Substring patterns that indicate false positives
FP_SUBSTRINGS: List[str] = [
    "serum c3",
    "serum c4",
    "serum c5",
    "serum igg",
    "serum iga",
    "serum igm",
    "complement bio",
    "complement system",
    "activation product",
    "normal serum",
    "plasma c3",
    "medicines agency",
    "pharmaceutical",
    "anaphylatoxin",
    "sc5b-9",
    "sc5b9",
    "c5b-9",
    "c5b9",
    # Animal/natural product false positives
    "musk deer",
    "musk secretion",
    "brand of fluoride",
    # Oncoprotein/genetic false positives
    "oncoprotein",
    "plasmid",
    "sulfotransferase",
    # Biological markers
    "end products, advanced",
    "glycation end",
]

# Common drug abbreviations mapped to their canonical full names
DRUG_ABBREVIATIONS: Dict[str, str] = {
    # Immunosuppressants
    "mtx": "methotrexate",
    "aza": "azathioprine",
    "mmf": "mycophenolate mofetil",
    "cspa": "cyclosporine",
    "csa": "cyclosporine",
    "cyc": "cyclophosphamide",
    "ctx": "cyclophosphamide",
    "rtx": "rituximab",
    # Corticosteroids
    "pred": "prednisolone",
    "mpd": "methylprednisolone",
    "dex": "dexamethasone",
    "hc": "hydrocortisone",
    # Common chemotherapy
    "5-fu": "fluorouracil",
    "5fu": "fluorouracil",
    "dox": "doxorubicin",
    "cis": "cisplatin",
    "carbo": "carboplatin",
    "pacl": "paclitaxel",
    "vcr": "vincristine",
    "vbl": "vinblastine",
    # Antibiotics
    "amox": "amoxicillin",
    "augmentin": "amoxicillin clavulanate",
    "vanco": "vancomycin",
    "gent": "gentamicin",
    "ceftx": "ceftriaxone",
    "tmp-smx": "trimethoprim sulfamethoxazole",
    "bactrim": "trimethoprim sulfamethoxazole",
    # Anticoagulants
    "ufh": "unfractionated heparin",
    "lmwh": "low molecular weight heparin",
    # Biologics
    "ivig": "intravenous immunoglobulin",
    "scig": "subcutaneous immunoglobulin",
    "tnfi": "tumor necrosis factor inhibitor",
    # Partial name to full name mappings
    "mycophenolate": "mycophenolate mofetil",
    # Cardiovascular
    "asa": "aspirin",
    "atenol": "atenolol",
    "ntg": "nitroglycerin",
    "acei": "angiotensin converting enzyme inhibitor",
    "arb": "angiotensin receptor blocker",
    # Pain management
    "apap": "acetaminophen",
    "nsaid": "nonsteroidal anti-inflammatory drug",
    # Diabetes
    "met": "metformin",
    # Other common
    "ppi": "proton pump inhibitor",
    "h2ra": "h2 receptor antagonist",
}


# Consumer drug misspellings and regional brand variants → canonical names
# Used by DrugDetector to expand FlashText matching for social media/patient text
CONSUMER_DRUG_VARIANTS: Dict[str, str] = {
    # Statin misspellings
    "sinivastatin": "simvastatin",
    "zocar": "simvastatin",
    "zorcor": "simvastatin",
    "liptor": "atorvastatin",
    "lipitors": "atorvastatin",
    "pravochol": "pravastatin",
    "mevacore": "lovastatin",
    # NSAID/analgesic misspellings
    "asprin": "aspirin",
    "alleve": "naproxen",
    "relefen": "nabumetone",
    "artrotec": "diclofenac",
    "capsacian": "capsaicin",
    "hydrocodine": "hydrocodone",
    "propain": "paracetamol",
    # Other common misspellings
    "insalin": "insulin",
    "trazadone": "trazodone",
    "testonrone": "testosterone",
    "ezetimbe": "ezetimibe",
    "naicin": "niacin",
    "actose": "pioglitazone",
    "capiten": "captopril",
    "glcotrol": "glipizide",
    # AU/NZ consumer brand names
    "panadeine": "paracetamol",
    "panadeine forte": "paracetamol",
    "mypaid forte": "paracetamol",
    "pamprin": "pamabrom",
}

# Multi-word consumer drug patterns not typically in clinical lexicons
CONSUMER_DRUG_PATTERNS: List[str] = [
    "birth control pill",
    "birth control pills",
    "flu jab",
    "steroid shots",
    "steroid shot",
    "vitamin c",
    "vit c",
    "omega 3",
    "coq10",
    "co q 10",
    "coenzyme q10",
    "fish oil",
    "red yeast rice",
    "cider vinegar",
]


__all__ = [
    "BACTERIA_ORGANISMS",
    "VACCINE_TERMS",
    "CREDENTIALS",
    "BIOLOGICAL_ENTITIES",
    "PHARMA_COMPANY_NAMES",
    "COMMON_WORDS",
    "ORGANIZATIONS",
    "BODY_PARTS",
    "TRIAL_STATUS_TERMS",
    "EQUIPMENT_PROCEDURES",
    "ALWAYS_FILTER",
    "NER_FALSE_POSITIVES",
    "NON_DRUG_ALLCAPS",
    "BIOLOGICAL_SUFFIXES",
    "FP_SUBSTRINGS",
    "DRUG_ABBREVIATIONS",
    "CONSUMER_DRUG_VARIANTS",
    "CONSUMER_DRUG_PATTERNS",
]
